version: "3.9"

services:
  api:
    container_name: super_timesheet_api
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/home/api
      - /home/api/node_modules
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    container_name: super_timesheet_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
